import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{Search,ShoppingBag,Heart,User,Menu,X,ChevronDown,Plus,Minus,Trash2,ArrowRight,ShieldCheck,Truck,RotateCcw,Settings,Package,Users,Image as ImageIcon,LogOut}from"lucide-react";
import"./styles.css";

const seed=[
{id:1,name:"Lawn Signature 3 Piece",cat:"Lawn 3PC",price:2799,old:4399,stock:18,badge:"20% OFF",img:"https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=88"},
{id:2,name:"Embroidered Summer Set",cat:"Lawn 3PC",price:3199,old:4599,stock:12,badge:"NEW",img:"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=88"},
{id:3,name:"Printed Luxe Shirt",cat:"Shirts",price:1899,old:2499,stock:26,badge:"BEST SELLER",img:"https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=88"},
{id:4,name:"Ready To Wear Ensemble",cat:"Ready To Wear",price:2499,old:2999,stock:9,badge:"20% OFF",img:"https://images.unsplash.com/photo-1585488433779-8c0f0b0b0a74?auto=format&fit=crop&w=1000&q=88"},
{id:5,name:"Luxury Embroidered Set",cat:"Luxury",price:4299,old:5499,stock:7,badge:"EXCLUSIVE",img:"https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1000&q=88"},
{id:6,name:"Premium Linen 2 Piece",cat:"Winter",price:2899,old:3499,stock:15,badge:"NEW",img:"https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1000&q=88"}
];
const money=n=>"PKR "+Number(n).toLocaleString();
function App(){
 const[products,setProducts]=useState(()=>JSON.parse(localStorage.getItem("atelier_products")||"null")||seed);
 const[orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem("atelier_orders")||"[]"));
 const[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("atelier_cart")||"[]"));
 const[wish,setWish]=useState(()=>JSON.parse(localStorage.getItem("atelier_wish")||"[]"));
 const[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[cartOpen,setCartOpen]=useState(false),[admin,setAdmin]=useState(false),[checkout,setCheckout]=useState(false),[menu,setMenu]=useState(false),[editing,setEditing]=useState(null);
 useEffect(()=>localStorage.setItem("atelier_products",JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem("atelier_orders",JSON.stringify(orders)),[orders]);
 useEffect(()=>localStorage.setItem("atelier_cart",JSON.stringify(cart)),[cart]);
 useEffect(()=>localStorage.setItem("atelier_wish",JSON.stringify(wish)),[wish]);
 const shown=useMemo(()=>products.filter(p=>(filter==="All"||p.cat===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,filter,query]);
 const add=p=>{setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:Math.min(i.q+1,p.stock)}:i):[...c,{...p,q:1}]});setCartOpen(true)};
 const total=cart.reduce((s,p)=>s+p.price*p.q,0),count=cart.reduce((s,p)=>s+p.q,0);
 const saveOrder=data=>{const o={id:"ORD-"+Date.now().toString().slice(-7),date:new Date().toLocaleString(),items:cart,total,status:"New",customer:data};setOrders(x=>[o,...x]);setCart([]);setCheckout(false);setCartOpen(false);alert("Order placed successfully: "+o.id)};
 const removeProduct=id=>setProducts(x=>x.filter(p=>p.id!==id));
 return <div>
  <div className="announce">FREE SHIPPING ON ORDERS ABOVE PKR 2,500 <span>•</span> EASY RETURNS</div>
  <header><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo">ATELIER<span>+</span></div>
   <nav className={menu?"open":""}>{["New In","Lawn 3PC","Shirts","Ready To Wear","Luxury","Winter","Sale"].map((x,i)=><button key={x} onClick={()=>{setFilter(x==="New In"||x==="Sale"?"All":x);setMenu(false)}}>{x}{i>0&&i<6?<ChevronDown size={13}/>:null}</button>)}</nav>
   <div className="actions"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></div><button className="icon" onClick={()=>alert("Customer account is ready for authentication integration.")}><User/></button><button className="icon" onClick={()=>alert(wish.length+" saved item(s)")}><Heart/><b>{wish.length}</b></button><button className="icon" onClick={()=>setCartOpen(true)}><ShoppingBag/><b>{count}</b></button><button className="adminBtn" onClick={()=>setAdmin(true)}><Settings size={16}/></button></div>
  </header>
  <main>
   <section className="hero"><div className="heroCopy"><p className="eyebrow">THE NEW SEASON</p><h1>Elegance,<br/><em>reimagined.</em></h1><p>Contemporary Pakistani fashion designed for effortless everyday luxury.</p><button className="primary" onClick={()=>document.getElementById("shop").scrollIntoView({behavior:"smooth"})}>SHOP COLLECTION <ArrowRight size={17}/></button></div></section>
   <section className="intro"><p className="eyebrow">CURATED FOR YOU</p><h2>New season. New attitude.</h2><p>Discover refined silhouettes, expressive prints and premium fabrics.</p></section>
   <section id="shop" className="shop"><div className="sectionHead"><div><p className="eyebrow">SHOP</p><h2>Latest Collection</h2></div><div className="filters">{["All","Lawn 3PC","Shirts","Ready To Wear","Luxury","Winter"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
    <div className="grid">{shown.map(p=><article className="card" key={p.id}><div className="photo"><img src={p.img} alt={p.name}/><span>{p.badge}</span><button className="wish" onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}>{wish.includes(p.id)?"♥":"♡"}</button><button className="quick" onClick={()=>add(p)} disabled={!p.stock}>{p.stock?"ADD TO BAG":"SOLD OUT"}</button></div><div className="meta"><p>{p.cat}</p><h3>{p.name}</h3><strong>{money(p.price)}</strong> <del>{money(p.old)}</del><small>{p.stock} available</small></div></article>)}</div></section>
   <section className="trust"><div><Truck/><b>Fast Delivery</b><span>Nationwide shipping</span></div><div><ShieldCheck/><b>Secure Checkout</b><span>Protected order data</span></div><div><RotateCcw/><b>Easy Returns</b><span>Simple return process</span></div></section>
   <section className="feature"><div><p className="eyebrow">THE ATELIER EDIT</p><h2>Made to be remembered.</h2><p>Statement pieces, considered details and versatile styling for every occasion.</p><button className="outline" onClick={()=>setFilter("Luxury")}>EXPLORE LUXURY <ArrowRight size={17}/></button></div></section>
   <section className="categories"><p className="eyebrow">EXPLORE</p><h2>Shop by mood</h2><div className="catgrid">{["Lawn 3PC","Ready To Wear","Luxury","Winter"].map((x,i)=><button key={x} onClick={()=>{setFilter(x);document.getElementById("shop").scrollIntoView({behavior:"smooth"})}}><img src={products[(i+2)%products.length].img}/><span>{x}<ArrowRight size={16}/></span></button>)}</div></section>
   <section className="newsletter"><p className="eyebrow">STAY IN THE LOOP</p><h2>First access to every drop.</h2><div><input placeholder="Your email address"/><button className="primary">SUBSCRIBE</button></div></section>
  </main>
  <footer><div className="logo">ATELIER<span>+</span></div><div><h4>SHOP</h4><p>New In</p><p>Collections</p><p>Sale</p></div><div><h4>HELP</h4><p>Shipping</p><p>Returns</p><p>Contact</p></div><div><h4>FOLLOW</h4><p>Instagram</p><p>Facebook</p><p>WhatsApp</p></div><small>© 2026 Atelier+. All rights reserved.</small></footer>
  {cartOpen&&<><div className="shade" onClick={()=>setCartOpen(false)}/><aside className="drawer"><div className="drawerHead"><h2>Your Bag</h2><button className="icon" onClick={()=>setCartOpen(false)}><X/></button></div>{!cart.length?<div className="empty">Your bag is empty.</div>:<><div className="bagList">{cart.map(p=><div className="line" key={p.id}><img src={p.img}/><div><h4>{p.name}</h4><p>{money(p.price)}</p><div className="qty"><button onClick={()=>setCart(c=>c.map(i=>i.id===p.id?{...i,q:Math.max(1,i.q-1)}:i))}><Minus size={14}/></button><span>{p.q}</span><button onClick={()=>setCart(c=>c.map(i=>i.id===p.id?{...i,q:Math.min(p.stock,i.q+1)}:i))}><Plus size={14}/></button><button onClick={()=>setCart(c=>c.filter(i=>i.id!==p.id))}><Trash2 size={14}/></button></div></div></div>)}</div><div className="checkout"><div><span>Subtotal</span><b>{money(total)}</b></div><button className="primary" onClick={()=>setCheckout(true)}>CHECKOUT <ArrowRight size={17}/></button></div></>}</aside></>}
  {checkout&&<Checkout total={total} onClose={()=>setCheckout(false)} onSubmit={saveOrder}/>}
  {admin&&<Admin products={products} orders={orders} setProducts={setProducts} setOrders={setOrders} editing={editing} setEditing={setEditing} removeProduct={removeProduct} onClose={()=>setAdmin(false)}/>}
 </div>
}
function Checkout({total,onClose,onSubmit}){const[f,setF]=useState({name:"",phone:"",city:"",address:"",payment:"Cash on Delivery"});const ok=Object.values(f).every(Boolean);return <div className="modalShade"><div className="modal"><div className="modalHead"><h2>Checkout</h2><button className="icon" onClick={onClose}><X/></button></div><div className="formGrid">{[["name","Full name"],["phone","Mobile / WhatsApp"],["city","City"],["address","Complete delivery address"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><label>Payment<select value={f.payment} onChange={e=>setF({...f,payment:e.target.value})}><option>Cash on Delivery</option><option>JazzCash</option><option>Easypaisa</option><option>Bank Transfer</option></select></label><div className="totalRow"><b>Total</b><strong>{money(total)}</strong></div><button className="primary full" disabled={!ok} onClick={()=>onSubmit(f)}>PLACE ORDER</button></div></div>}
function Admin({products,orders,setProducts,setOrders,editing,setEditing,removeProduct,onClose}){const[tab,setTab]=useState("dashboard");const blank={id:Date.now(),name:"New Product",cat:"Lawn 3PC",price:0,old:0,stock:0,badge:"NEW",img:""};return <div className="adminShade"><div className="admin"><aside className="adminSide"><div className="logo">ATELIER<span>+</span></div><button onClick={()=>setTab("dashboard")}><Package/>Dashboard</button><button onClick={()=>setTab("products")}><ImageIcon/>Products</button><button onClick={()=>setTab("orders")}><ShoppingBag/>Orders</button><button onClick={()=>setTab("customers")}><Users/>Customers</button><button onClick={onClose}><LogOut/>Close</button></aside><section className="adminMain"><div className="adminTop"><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><button className="icon" onClick={onClose}><X/></button></div>{tab==="dashboard"&&<div className="stats"><div><b>{products.length}</b><span>Products</span></div><div><b>{orders.length}</b><span>Orders</span></div><div><b>{products.reduce((s,p)=>s+p.stock,0)}</b><span>Stock Units</span></div><div><b>{money(orders.reduce((s,o)=>s+o.total,0))}</b><span>Order Value</span></div></div>}{tab==="products"&&<><button className="primary" onClick={()=>setEditing(blank)}>+ ADD PRODUCT</button><div className="table">{products.map(p=><div className="tr" key={p.id}><img src={p.img}/><span><b>{p.name}</b><small>{p.cat} · {money(p.price)} · {p.stock} stock</small></span><button onClick={()=>setEditing(p)}>Edit</button><button className="danger" onClick={()=>removeProduct(p.id)}>Delete</button></div>)}</div></>}{tab==="orders"&&<div className="table">{orders.length?orders.map(o=><div className="tr" key={o.id}><span><b>{o.id}</b><small>{o.customer.name} · {o.customer.phone} · {o.date}</small></span><strong>{money(o.total)}</strong><select value={o.status} onChange={e=>setOrders(os=>os.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}><option>New</option><option>Confirmed</option><option>Packed</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select></div>):<p>No orders yet.</p>}</div>}{tab==="customers"&&<div className="emptyAdmin">Customer records are created from checkout orders. No customer data is sent anywhere by this frontend.</div>}</section></div>{editing&&<ProductEditor p={editing} onClose={()=>setEditing(null)} onSave={p=>{setProducts(x=>x.some(i=>i.id===p.id)?x.map(i=>i.id===p.id?p:i):[...x,p]);setEditing(null)}}/>}</div>}
function ProductEditor({p,onClose,onSave}){const[x,setX]=useState(p);return <div className="modalShade"><div className="modal"><div className="modalHead"><h2>Product Editor</h2><button className="icon" onClick={onClose}><X/></button></div><div className="formGrid">{["name","cat","price","old","stock","badge","img"].map(k=><label key={k}>{k.toUpperCase()}<input value={x[k]} onChange={e=>setX({...x,[k]:["price","old","stock"].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</div><p className="hint">Paste your original product photo URL in IMAGE. In production this field can be connected to your storage uploader.</p><button className="primary full" onClick={()=>onSave(x)}>SAVE PRODUCT</button></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
