import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{Search,ShoppingBag,Heart,User,Menu,X,ChevronDown,Plus,Minus,Trash2,ArrowRight,ShieldCheck,Truck,RotateCcw,Settings,Package,Users,Image as ImageIcon,LogOut,CheckCircle,Lock,UserPlus}from"lucide-react";
import{supabase}from"./lib/supabase";
import"./styles.css";

// Original starter catalogue preserved from the first project build.
const starterCatalog=[
{id:"starter-1",name:"Lawn Signature 3 Piece",cat:"Lawn 3PC",price:2799,old:4399,stock:18,badge:"20% OFF",img:"https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=88"},
{id:"starter-2",name:"Embroidered Summer Set",cat:"Lawn 3PC",price:3199,old:4599,stock:12,badge:"NEW",img:"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=88"},
{id:"starter-3",name:"Printed Luxe Shirt",cat:"Shirts",price:1899,old:2499,stock:26,badge:"BEST SELLER",img:"https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=88"},
{id:"starter-4",name:"Ready To Wear Ensemble",cat:"Ready To Wear",price:2499,old:2999,stock:9,badge:"20% OFF",img:"https://images.unsplash.com/photo-1585488433779-8c0f0b0b0a74?auto=format&fit=crop&w=1000&q=88"},
{id:"starter-5",name:"Luxury Embroidered Set",cat:"Luxury",price:4299,old:5499,stock:7,badge:"EXCLUSIVE",img:"https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1000&q=88"},
{id:"starter-6",name:"Premium Linen 2 Piece",cat:"Winter",price:2899,old:3499,stock:15,badge:"NEW",img:"https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1000&q=88"}
];
const categoryMap={
 "Summer 26":["Lawn 3PC","2Pcs Plain Trouser","Ready To Wear","Shirt & 2Pcs"],
 "Lawn 3PC":["SANAM","Kashish","Afsana","Laraib","DilKash","JANNAT","Delnaz","Noor","Zulaykha","Makhmal","FARIS","ZARA","Gulabo","Kismat","ISHARA","JANAN","Didar","Aizal","GULL RUKH","Husna","Sapna","GULAAL","Gul Bahar","Suhana","Gull e Zahra","Mahtab","LAAL","Noor Jahan","Gul e Khaas","Guluna","kahani","LARA","Gul Nar","Gul Badan","Luxury"],
 "Luxury":["Gulbahar","Gulshan","Surkhaab","Nayab","Resham","Layla","Jazmin","Aura","Darshan"],
 "Stitched":["Ready To Wear"],
 "Winter":["KHADDAR","Golden Shamray","Linen Bana Dora","LINEN 2Pcs"]
};
const money=n=>"PKR "+Number(n||0).toLocaleString();
const makeOrderNumber=()=>`NC-${Date.now().toString().slice(-9)}`;
const normalized=(p)=>({id:p.id,name:p.name,cat:p.category??p.cat??"Lawn 3PC",price:Number(p.sale_price??p.price??0),old:Number(p.price??0),stock:Number(p.stock??0),badge:p.badge??"",img:p.image_url??p.img??"",description:p.description??""});

function App(){
 const[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[wish,setWish]=useState(()=>JSON.parse(localStorage.getItem("nawal_wish")||"[]"));
 const[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("nawal_cart")||"[]"));
 const[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[cartOpen,setCartOpen]=useState(false),[admin,setAdmin]=useState(false),[checkout,setCheckout]=useState(false),[menu,setMenu]=useState(false),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState("login"),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 const whatsapp="923039249849";
 useEffect(()=>{localStorage.setItem("nawal_cart",JSON.stringify(cart));},[cart]);
 useEffect(()=>{localStorage.setItem("nawal_wish",JSON.stringify(wish));},[wish]);
 useEffect(()=>{document.body.style.overflow=(selected||checkout||authOpen||admin)?"hidden":"";return()=>{document.body.style.overflow=""};},[selected,checkout,authOpen,admin]);
 useEffect(()=>{(async()=>{if(!supabase){setProducts(starterCatalog);setLoading(false);return;}const{data:{session}}=await supabase.auth.getSession();setUser(session?.user||null);if(session?.user)await loadProfile(session.user.id);await loadProducts();setLoading(false);const{data:{subscription}}=supabase.auth.onAuthStateChange(async(_,s)=>{setUser(s?.user||null);if(s?.user)await loadProfile(s.user.id);else setProfile(null);});return()=>subscription.unsubscribe();})()},[]);
 async function loadProducts(){if(!supabase){setProducts(starterCatalog);return;}const{data,error}=await supabase.from("products").select("*").eq("is_active",true).order("created_at",{ascending:false});if(error){setProducts([]);setNotice(error.message);return;}setProducts((data||[]).map(normalized));setCart(c=>c.filter(i=>!i.id||typeof i.id!=="string"?false:true).filter(i=>(data||[]).some(p=>p.id===i.id)).map(i=>{const p=(data||[]).find(x=>x.id===i.id);return {...normalized(p),q:Math.min(i.q,p.stock)}}));}
 async function loadProfile(id){if(!supabase)return;const{data}=await supabase.from("profiles").select("*").eq("id",id).maybeSingle();setProfile(data||null);}
 const shown=useMemo(()=>products.filter(p=>{const sale=filter==="Sale"?(p.old>p.price):true;const match=filter==="All"||filter==="Sale"?sale:p.cat===filter;return match&&p.name.toLowerCase().includes(query.toLowerCase());}),[products,filter,query]);
 const goShop=(next="All")=>{setQuery("");setFilter(next);setMenu(false);requestAnimationFrame(()=>document.getElementById("shop")?.scrollIntoView({behavior:"smooth",block:"start"}));};
 const goChild=(parent,child)=>{setQuery(child==="Luxury"?"":child);setFilter(parent);setMenu(false);requestAnimationFrame(()=>document.getElementById("shop")?.scrollIntoView({behavior:"smooth",block:"start"}));};
 const add=p=>{if(!p.stock)return;setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:Math.min(i.q+1,p.stock)}:i):[...c,{...p,q:1}]});setCartOpen(true);};
 const total=cart.reduce((s,p)=>s+p.price*p.q,0),count=cart.reduce((s,p)=>s+p.q,0);
 function startCheckout(){if(!cart.length)return;setCheckout(true);}
 async function ensureAuthThenOrder(data){if(!supabase){setNotice("Supabase is not configured for this deployment.");return;}if(!user){setAuthMode("login");setAuthOpen(true);return;}await placeOrder(data);}
 async function placeOrder(data){if(!supabase||!user)return;const orderNumber=makeOrderNumber();const{data:order,error}=await supabase.from("orders").insert({order_number:orderNumber,customer_id:user.id,customer_name:data.name,customer_phone:data.phone,customer_email:user.email||null,city:data.city,address:data.address,notes:data.notes||null,subtotal:total,shipping:0,total,payment_method:data.payment,status:"new"}).select().single();if(error){setNotice(error.message);return;}const items=cart.map(p=>({order_id:order.id,product_id:p.id,product_name:p.name,product_image:p.img,price:p.price,quantity:p.q,total:p.price*p.q}));const{error:itemError}=await supabase.from("order_items").insert(items);if(itemError){setNotice(itemError.message);return;}const message=[`NAWAL COLLECTIONS — ORDER ${orderNumber}`,"",...cart.map((p,i)=>`${i+1}. ${p.name} × ${p.q} — ${money(p.price*p.q)}`),"",`Total: ${money(total)}`,`Name: ${data.name}`,`Phone: ${data.phone}`,`City: ${data.city}`,`Address: ${data.address}`,`Payment: ${data.payment}`,`Notes: ${data.notes||"-"}`].join("\n");setCart([]);setCheckout(false);setCartOpen(false);window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer");setNotice(`Order ${orderNumber} saved successfully.`);}
 async function signOut(){if(supabase)await supabase.auth.signOut();setAdmin(false);}
 async function openAdmin(){if(!user){setAuthMode("login");setAuthOpen(true);setNotice("Login with the admin account to open the dashboard.");return;}await loadProfile(user.id);if(profile?.role!=="admin"){setNotice("Admin access is available only to an authorized administrator.");return;}setAdmin(true);}
 async function removeProduct(id){if(!supabase||profile?.role!=="admin")return;const{error}=await supabase.from("products").update({is_active:false}).eq("id",id);if(error)setNotice(error.message);else loadProducts();}
 async function saveProduct(p){if(!supabase||profile?.role!=="admin")return;const payload={name:p.name,description:p.description||"",category:p.cat,price:Number(p.old||p.price||0),sale_price:Number(p.price||0),stock:Number(p.stock||0),image_url:p.img||null,badge:p.badge||"",is_active:true};const req=p.id?supabase.from("products").update(payload).eq("id",p.id):supabase.from("products").insert(payload);const{error}=await req;if(error)setNotice(error.message);else{setEditing(null);loadProducts();}}
 return <div>
  <div className="announce">FREE SHIPPING ON ORDERS ABOVE PKR 2,500 <span>•</span> EASY RETURNS</div>
  <header><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo">ATELIER<span>+</span></div>
   <nav className={menu?"open":""}>{["New In","Summer 26","Lawn 3PC","Luxury","Stitched","Winter","Sale"].map((x,i)=><div className="navItem" key={x}><button onClick={()=>goShop(x==="New In"?"All":x)}>{x}{i>0&&i<6?<ChevronDown size={13}/>:null}</button>{categoryMap[x]&&<div className="mega">{categoryMap[x].map(c=><button key={c} onClick={()=>goChild(x==="Summer 26"&&c==="Lawn 3PC"?"Lawn 3PC":x,c)}>{c}</button>)}</div>}</div>)}</nav>
   <div className="actions"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></div><button className="icon" onClick={()=>{setAuthMode("login");setAuthOpen(true)}}><User/></button><button className="icon" onClick={()=>setNotice(`${wish.length} saved item(s)`)}><Heart/><b>{wish.length}</b></button><button className="icon" onClick={()=>setCartOpen(true)}><ShoppingBag/><b>{count}</b></button><button className="adminBtn" onClick={openAdmin}><Settings size={16}/></button></div>
  </header>
  {notice&&<div className="noticeBar"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={15}/></button></div>}
  <main>
   <section className="hero"><div className="heroCopy"><p className="eyebrow">THE NEW SEASON</p><h1>Elegance,<br/><em>reimagined.</em></h1><p>Contemporary Pakistani fashion designed for effortless everyday luxury.</p><button className="primary" onClick={()=>goShop("All")}>SHOP COLLECTION <ArrowRight size={17}/></button></div></section>
   <section className="intro"><p className="eyebrow">CURATED FOR YOU</p><h2>New season. New attitude.</h2><p>Discover refined silhouettes, expressive prints and versatile styling.</p></section>
   <section id="shop" className="shop"><div className="sectionHead"><div><p className="eyebrow">SHOP</p><h2>Latest Collection</h2></div><div className="filters">{["All","Lawn 3PC","Shirts","Ready To Wear","Luxury","Winter","Sale"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
    <div className="grid">{loading?<p>Loading collection…</p>:shown.length?shown.map(p=><article className="card" key={p.id}><div className="photo" onClick={()=>setSelected(p)} role="button" tabIndex={0} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&setSelected(p)}><img src={p.img} alt={p.name}/>{p.badge&&<span>{p.badge}</span>}{p.stock<=0&&<span className="soldBadge">SOLD OUT</span>}</div><button className="wish" onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}>{wish.includes(p.id)?"♥":"♡"}</button><button className="quick" onClick={()=>add(p)} disabled={!p.stock}>{p.stock?"ADD TO BAG":"SOLD OUT"}</button><div className="meta"><p>{p.cat}</p><h3 onClick={()=>setSelected(p)}>{p.name}</h3><strong>{money(p.price)}</strong> {p.old>p.price&&<del>{money(p.old)}</del>}<small>{p.stock>0?`${p.stock} available`:"Sold out"}</small></div></article>):<div className="emptyCollection"><h3>No products found.</h3><p>Publish products from Admin → Products to populate this collection.</p></div>}</div></section>
   <section className="trust"><div><Truck/><b>Fast Delivery</b><span>Nationwide shipping</span></div><div><ShieldCheck/><b>Secure Checkout</b><span>Protected order data</span></div><div><RotateCcw/><b>Easy Returns</b><span>Simple return process</span></div></section>
   <section className="feature"><div><p className="eyebrow">THE ATELIER EDIT</p><h2>Made to be remembered.</h2><p>Statement pieces, considered details and versatile styling for every occasion.</p><button className="outline" onClick={()=>goShop("Luxury")}>EXPLORE LUXURY <ArrowRight size={17}/></button></div></section>
   <section className="categories"><p className="eyebrow">EXPLORE</p><h2>Shop by mood</h2><div className="catgrid">{["Lawn 3PC","Ready To Wear","Luxury","Winter"].map((x,i)=>{const img=products.find(p=>p.cat===x)?.img||starterCatalog[(i+1)%starterCatalog.length].img;return <button key={x} onClick={()=>goShop(x)}><img src={img} alt={x}/><span>{x}<ArrowRight size={16}/></span></button>})}</div></section>
   <section className="newsletter"><p className="eyebrow">STAY IN THE LOOP</p><h2>First access to every drop.</h2><div><input placeholder="Your email address"/><button className="primary" onClick={()=>setNotice("Thank you. You're on the list.")}>SUBSCRIBE</button></div></section>
  </main>
  <footer><div className="logo">ATELIER<span>+</span></div><div><h4>SHOP</h4><button className="footerLink" onClick={()=>goShop("All")}>New In</button><button className="footerLink" onClick={()=>goShop("All")}>Collections</button><button className="footerLink" onClick={()=>goShop("Sale")}>Sale</button></div><div><h4>HELP</h4><p>Shipping</p><p>Returns</p><button className="footerLink" onClick={()=>window.open(`https://wa.me/${whatsapp}`,"_blank")}>Contact</button></div><div><h4>FOLLOW</h4><p>Instagram</p><p>Facebook</p><button className="footerLink" onClick={()=>window.open(`https://wa.me/${whatsapp}`,"_blank")}>WhatsApp</button></div><small>© 2026 NAWAL COLLECTIONS. All rights reserved. ALISHAIR5.</small></footer>
  {cartOpen&&<><div className="shade" onClick={()=>setCartOpen(false)}/><aside className="drawer"><div className="drawerHead"><h2>Your Bag</h2><button className="icon" onClick={()=>setCartOpen(false)}><X/></button></div>{!cart.length?<div className="empty">Your bag is empty.</div>:<><div className="bagList">{cart.map(p=><div className="line" key={p.id}><img src={p.img} alt={p.name}/><div><h4>{p.name}</h4><p>{money(p.price)}</p><div className="qty"><button onClick={()=>setCart(c=>c.map(i=>i.id===p.id?{...i,q:Math.max(1,i.q-1)}:i))}><Minus size={14}/></button><span>{p.q}</span><button onClick={()=>setCart(c=>c.map(i=>i.id===p.id?{...i,q:Math.min(p.stock,i.q+1)}:i))}><Plus size={14}/></button><button onClick={()=>setCart(c=>c.filter(i=>i.id!==p.id))}><Trash2 size={14}/></button></div></div></div>)}</div><div className="checkout"><div><span>Subtotal</span><b>{money(total)}</b></div><button className="primary" onClick={startCheckout}>CHECKOUT <ArrowRight size={17}/></button></div></>}</aside></>}
  {selected&&<ProductDetail p={selected} onClose={()=>setSelected(null)} onAdd={add}/>} 
  {checkout&&<Checkout total={total} user={user} onClose={()=>setCheckout(false)} onNeedAuth={()=>{setAuthMode("login");setAuthOpen(true)}} onSubmit={ensureAuthThenOrder}/>} 
  {authOpen&&<AuthModal mode={authMode} setMode={setAuthMode} onClose={()=>setAuthOpen(false)} onLoggedIn={()=>setAuthOpen(false)}/>} 
  {admin&&<Admin products={products} orders={orders} profile={profile} setProducts={setProducts} setOrders={setOrders} editing={editing} setEditing={setEditing} removeProduct={removeProduct} saveProduct={saveProduct} onClose={()=>setAdmin(false)} signOut={signOut}/>} 
 </div>
}

function ProductDetail({p,onClose,onAdd}){return <div className="modalShade" onClick={onClose}><div className="modal productDetail" onClick={e=>e.stopPropagation()}><div className="modalHead"><h2>{p.name}</h2><button className="icon" onClick={onClose}><X/></button></div><div className="productDetailGrid"><img className="detailImage" src={p.img} alt={p.name}/><div><p className="eyebrow">{p.cat}</p><h2>{p.name}</h2><div className="detailPrice"><strong>{money(p.price)}</strong>{p.old>p.price&&<del>{money(p.old)}</del>}</div><p>{p.description||"Premium collection piece from the current store catalogue."}</p><p><b>{p.stock>0?`${p.stock} available`:`SOLD OUT`}</b></p><button className="primary full" disabled={!p.stock} onClick={()=>{onAdd(p);onClose()}}>{p.stock?"ADD TO BAG":"SOLD OUT"}</button></div></div></div></div>}

function Checkout({total,onClose,onSubmit,user}){const[f,setF]=useState({name:"",phone:"",city:"",address:"",payment:"Cash on Delivery",notes:""});const[busy,setBusy]=useState(false);const valid=f.name&&f.phone&&f.city&&f.address;async function submit(){setBusy(true);await onSubmit(f);setBusy(false);}return <div className="modalShade"><div className="modal"><div className="modalHead"><h2>Checkout</h2><button className="icon" onClick={onClose}><X/></button></div>{!user&&<div className="checkoutGate"><Lock size={16}/> At the final step, login or create your account to complete the order.</div>}<div className="formGrid">{[["name","Full name"],["phone","Mobile / WhatsApp"],["city","City"],["address","Complete delivery address"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><label>Payment<select value={f.payment} onChange={e=>setF({...f,payment:e.target.value})}><option>Cash on Delivery</option><option>JazzCash</option><option>Easypaisa</option><option>Bank Transfer</option></select></label><label>Order notes<input value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="totalRow"><b>Total</b><strong>{money(total)}</strong></div><button className="primary full" disabled={busy||!valid} onClick={submit}>{busy?"PLEASE WAIT":"PLACE ORDER"}</button></div></div>}

function AuthModal({mode,setMode,onClose}){const[f,setF]=useState({email:"",password:"",name:"",phone:""});const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);async function submit(){if(!supabase)return;setBusy(true);setMsg("");try{if(mode==="signup"){const{error}=await supabase.auth.signUp({email:f.email,password:f.password,options:{data:{full_name:f.name,phone:f.phone}}});if(error)throw error;setMsg("Account created. Check your email if confirmation is enabled, then login here.");setMode("login");}else{const{error}=await supabase.auth.signInWithPassword({email:f.email,password:f.password});if(error)throw error;onClose();}}catch(e){setMsg(e.message)}finally{setBusy(false)}}return <div className="modalShade"><div className="modal authModal"><div className="modalHead"><h2>{mode==="login"?"Login to complete order":"Create your account"}</h2><button className="icon" onClick={onClose}><X/></button></div>{mode==="signup"&&<><label>Full name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Mobile / WhatsApp<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label></>}<label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{msg&&<div className="hint">{msg}</div>}<button className="primary full" disabled={busy||!f.email||!f.password} onClick={submit}>{busy?"PLEASE WAIT":mode==="login"?"LOGIN":"CREATE ACCOUNT"}</button><button className="linkBtn" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?<><UserPlus size={15}/> Create account</>:<><Lock size={15}/> I already have an account</>}</button></div></div>}

function Admin({products,orders,profile,setProducts,setOrders,editing,setEditing,removeProduct,saveProduct,onClose,signOut}){const[tab,setTab]=useState("dashboard");const blank={name:"",cat:"Lawn 3PC",price:0,old:0,stock:0,badge:"",img:"",description:""};return <div className="adminShade"><div className="admin"><aside className="adminSide"><div className="logo">NAWAL COLLECTIONS</div><button onClick={()=>setTab("dashboard")}><Package/>Dashboard</button><button onClick={()=>setTab("products")}><ImageIcon/>Products</button><button onClick={()=>setTab("orders")}><ShoppingBag/>Orders</button><button onClick={()=>setTab("customers")}><Users/>Customers</button><button onClick={signOut}><LogOut/>Logout</button><button onClick={onClose}><X/>Close</button></aside><section className="adminMain"><div className="adminTop"><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><button className="icon" onClick={onClose}><X/></button></div>{tab==="dashboard"&&<div className="stats"><div><b>{products.length}</b><span>Products</span></div><div><b>{orders.length}</b><span>Orders</span></div><div><b>{products.reduce((s,p)=>s+p.stock,0)}</b><span>Stock Units</span></div><div><b>{money(orders.reduce((s,o)=>s+Number(o.total||0),0))}</b><span>Order Value</span></div></div>}{tab==="products"&&<><button className="primary" onClick={()=>setEditing({...blank})}>+ ADD PRODUCT</button><div className="table">{products.map(p=><div className="tr" key={p.id}><img src={p.img} alt={p.name}/><span><b>{p.name}</b><small>{p.cat} · {money(p.price)} · {p.stock} stock</small></span><button onClick={()=>setEditing(p)}>Edit</button><button className="danger" onClick={()=>removeProduct(p.id)}>Delete</button></div>)}</div></>}{tab==="orders"&&<div className="table">{orders.length?orders.map(o=><div className="tr" key={o.id}><span><b>{o.order_number||o.id}</b><small>{o.customer_name||o.customer?.name||"Customer"} · {o.customer_phone||o.customer?.phone||""}</small></span><strong>{money(o.total)}</strong></div>):<p>No orders yet.</p>}</div>}{tab==="customers"&&<div className="emptyAdmin">Customers are created through the secure checkout/login flow.</div>}</section></div>{editing&&<ProductEditor p={editing} onClose={()=>setEditing(null)} onSave={saveProduct}/>}</div>}
function ProductEditor({p,onClose,onSave}){const[x,setX]=useState(p);return <div className="modalShade"><div className="modal"><div className="modalHead"><h2>Product Editor</h2><button className="icon" onClick={onClose}><X/></button></div><div className="formGrid">{[["name","PRODUCT NAME"],["cat","CATEGORY"],["price","SALE PRICE"],["old","REGULAR PRICE"],["stock","STOCK"],["badge","BADGE"],["img","IMAGE URL"]].map(([k,l])=><label key={k}>{l}<input value={x[k]??""} onChange={e=>setX({...x,[k]:["price","old","stock"].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</div><label>DESCRIPTION<textarea value={x.description||""} onChange={e=>setX({...x,description:e.target.value})}/></label><button className="primary full" onClick={()=>onSave(x)}>SAVE PRODUCT</button></div></div>}

createRoot(document.getElementById("root")).render(<App/>);
